export const mockRates = {
    "USD": "325",
    "QWE": "325",
    "DSA": "325",
    "ASD": "325",
    "RTY": "325",
    "TYU": "325",
    "IOP": "325",
    "AD": "325",
    "FGD": "325",
    "FJ": "325",
    "SMD": "325",
    "FD": "325",
    "KL": "325",
    ":DS": "325",
    "SDF": "325",
    "FNDJ": "325",
    "FDJK": "325",
    "FDN": "325",
    "ZAQ": "325",
    "DFJK": "325",
    "DF": "325",
    "DG": "325",
    "SDFG": "325",
    "DSF": "325",
    "LF": "325",
    "JHKLJ": "325",
    "HJN": "325",
    "JKHG": "325",
    "QGVD": "325",
    "<SNF>": "325",
    "FND": "325",
    "MFD": "325",
    "VM": "325",
    "NBV": "325",
    "BNSD": "325",
    "DSFF": "325",
    "MFDS": "325",
    "NSD": "325",
    "SMSD": "325",
    "SDQE": "325",
    "DSFA": "325",
    "SDFQ": "325",
}

export const mockCurrencies = [
    "USD",
    "QWE",
    "DSA",
    "ASD",
    "RTY",
    "TYU",
    "IOP",
    "AD",
    "FGD",
    "FJ",
    "SMD",
    "FD",
    "KL",
    ":DS",
    "SDF",
    "FNDJ",
    "FDJK",
    "FDN",
    "ZAQ",
    "DFJK",
    "DF",
    "DG",
    "SDFG",
    "DSF",
    "LF",
    "JHKLJ",
    "HJN",
    "JKHG",
    "QGVD",
    "<SNF",
    "FND",
    "MFD",
    "VM",
    "NBV",
    "BNSD",
    "DSFF",
    "MFDS",
    "NSD",
    "SMSD",
    "SDQE",
    "DSFA",
    "SDFQ"
]